[package]
name = "rs-exr"
version = "0.1.0"
authors = ["johannesvollmer <johannes.boenki@t-online.de>"]
edition = "2018"

[dependencies]
libflate = "*"
byteorder = "*"
bit_field = "*"
smallvec = "*"
half = { version = "1.4.0", features = ["std"] }
threadpool = "1.7.1"
num_cpus = "1.11.1"

[dev-dependencies]
bencher = "0.1.5"
image = "*" # required converting exr to png in tests

[[bench]]
name = "benches"
harness = false