[package]
name = "rs-exr"
version = "0.1.0"
authors = ["johannesvollmer <johannes.boenki@t-online.de>"]
edition = "2018"

[dependencies]
half = { version = "1.4.0", features = ["std"] }
lebe = { git = "http://github.com/johannesvollmer/lebe" }
libflate = "0.1.27"

bit_field = "0.10.0"
smallvec = "1.1.0"
rayon = "1.2.1"

[dev-dependencies]
bencher = "0.1.5"
image = "0.23.0-preview.0" # required converting exr to png in tests

[[bench]]
name = "benches"
harness = false