[package]
name = "exr"
version = "0.1.0"
authors = ["johannesvollmer <johannes596@t-online.de>"]
edition = "2018"

[dependencies]
# data types
half = "1.4.0"
smallvec = "1.1.0"

# serialization
lebe = { git = "http://github.com/johannesvollmer/lebe" }
bit_field = "0.10.0"

# zlib compression
libflate = "0.1.27"

# simple concurrency
rayon = "1.2.1"


[dev-dependencies]
bencher = "0.1.5"
image = "0.23.0-preview.0"
walkdir = "2.2.9"

[[bench]]
name = "benches"
harness = false

[[bench]]
name = "profiling"
harness = false

# release with fastest runtime speed
[profile.release]
opt-level = 3
lto = true
debug = false
codegen-units = 1

# test with fast runtime speed and moderate build speed
[profile.dev]
opt-level = 3
debug = true

# bench with fastest runtime speed
[profile.bench]
opt-level = 3
lto = true
debug = true
codegen-units = 1
