[package]
name = "rs-exr"
version = "0.1.0"
authors = ["johannesvollmer <johannes.boenki@t-online.de>"]

[dependencies]
seek_bufread = "*"
libflate = "*"
byteorder = "*"
bit_field = "*"
smallvec = "*"
half = "*"