[package]
name = "rs-exr"
version = "0.1.0"
authors = ["johannesvollmer <johannes.boenki@t-online.de>"]
edition = "2018"

[dependencies]
seek_bufread = "*"
libflate = "*"
byteorder = "*"
bit_field = "*" # TODO
smallvec = "*"
half = { version = "1.4.0", features = ["std"] }
rayon = "1.2.1"

[dev-dependencies]
image = "*" # required for testing, for converting exr to png