name: Rust

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose


  macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  # github actions does not support big endian systems directly, but it does support QEMU.
  # so we install qemu, cross-compile to sparc64, and then run the tests in an emulated sparc64.
  # see https://github.com/wasm3/wasm3/blob/main/.github/workflows/tests.yml#L318
  mips:
    runs-on: ubuntu-20.04
    name: mips-unknown-linux-gnu
    timeout-minutes: 25

    # we are using the cross project for cross compilation to sparc64:
    # https://github.com/cross-rs/cross

    steps:
      - uses: actions/checkout@v2

      - name: Install cross-rs/cross
        run: |
          cargo install cross
          sudo systemctl start docker

      - name: Cross-Compile project to mips-unknown-linux-gnu
        run: |
          cross build --target=mips-unknown-linux-gnu --verbose

      # https://github.com/cross-rs/cross#supported-targets
      - name: Cross-Run Tests in mips-unknown-linux-gnu using Qemu
        run: |
          cross test --target mips-unknown-linux-gnu --verbose
